engines:
  csslint:
    enabled: true
    ratings:
      paths:
      - "**.css" 
  eslint:
    enabled: true
    ratings:
      paths:
      - "**.js"
  phpcodesniffer:
    enabled: true
    config:
      file_extensions: "php,inc,lib"
      standard: "PSR2"
    ratings:
      paths:
      - "**.php"

exclude_paths:
- GPL_LIB/**/*
- features/**/*
- doc/**/*
- tmpl/**/*
- log/**/*
- config/**/*
- logrotate/**/*
- snmptrapd/**/*
- varinstall/**/*
