engines:
  csslint:
    enabled: true

  ratings:
    paths:
      - "**.css"
engines: 
  eslint:
    enabled: true

ratings:
   paths:
   - "**.js"

engines:
  phpcodesniffer:
    enabled: true
    config:
      file_extensions: "php"
      standard: "PSR2"

ratings:
  paths:
  - "**.php"

exclude_paths:
- GPL_LIB/**/*
- features/**/*
- doc/**/*
- tmpl/**/*
- log/**/*
- config/**/*
- logrotate/**/*
- snmptrapd/**/*
- varinstall/**/*
