engines:
  phpcodesniffer:
    enabled: true
    config:
      file_extensions: "php,inc,lib"
      standard: "PSR2"
      exclude_paths:
      - GPL_LIB/
      - features/
ratings:
  paths:
  - "**.php"
