parameters:

services:
  _defaults:
    public: false
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, controller...

  CentreonAutoDiscovery\:
    resource: '../../src/CentreonAutoDiscovery/*'

  CentreonAutoDiscovery\Domain\Provider\Interfaces\ProviderRepositoryInterface:
    class: CentreonAutoDiscovery\Infrastructure\Provider\ProviderRepositoryRDB
    calls:
      - method: setSqlRequestTranslator
        arguments: ['@sqlRequestTranslator']


  _instanceof:
    CentreonAutoDiscovery\Domain\Mapper\Interfaces\MapperInterface:
      tags: ['centreon.auto_discovery.mapper']

  CentreonAutoDiscovery\Application\Controller\MapperController:
    calls:
      - method: addMappers
        arguments:
          - !tagged centreon.auto_discovery.mapper

  CentreonAutoDiscovery\Domain\Mapper\Interfaces\MapperServiceInterface:
    class: CentreonAutoDiscovery\Domain\Mapper\MapperService
    public: true

  CentreonAutoDiscovery\Domain\Mapper\Interfaces\MapperRepositoryInterface:
    class: CentreonAutoDiscovery\Infrastructure\Mapper\MapperRepositoryRDB
