Centreon\Domain\Filter\FilterCriteria:
    properties:
        name:
            type: string
            groups: [filter_main]
        type:
            type: string
            groups: [filter_main]
        value:
            type: string
            groups: [filter_main]
        objectType:
            type: string
            groups: [filter_main]
